INSERT INTO STATUS (ID, NAME) VALUES
    (1, 'RECOGIDO EN ALMACÉN'),
    (2, 'EN REPARTO'),
    (3, 'INCIDENCIA EN ENTREGA'),
    (4, 'ENTREGADO');

INSERT INTO STATUS_TRANSITIONS (STATUS_FROM, STATUS_TO) VALUES
    (1, 2),
    (2, 3),
    (2, 4),
    (3, 2);