CREATE TABLE IF NOT EXISTS STATUS (
    ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ORDERS (
    ID BIGINT PRIMARY KEY,
    STATUS_ID INT,
    CREATED_AT TIMESTAMP NOT NULL,
    FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID)
);

CREATE TABLE IF NOT EXISTS ORDERS_TRACKING (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID BIGINT NOT NULL,
    PREVIOUS_STATUS INT,
    CURRENT_STATUS INT NOT NULL,
    EVENT_TIMESTAMP TIMESTAMP NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID),
    FOREIGN KEY (PREVIOUS_STATUS) REFERENCES STATUS (ID),
    FOREIGN KEY (CURRENT_STATUS) REFERENCES STATUS (ID)
);

CREATE TABLE IF NOT EXISTS STATUS_TRANSITIONS (
    STATUS_FROM INT NOT NULL,
    STATUS_TO INT NOT NULL,
    PRIMARY KEY (STATUS_FROM, STATUS_TO),
    FOREIGN KEY (STATUS_FROM) REFERENCES STATUS (ID),
    FOREIGN KEY (STATUS_TO) REFERENCES STATUS (ID)
);